package erpims.modelims.imseo;

import erpfms.modelfms.fmseo.GlChartOfAccountsImpl;

import erpglobals.modelglobals.ERPEntityImpl;

import java.math.BigDecimal;

import java.sql.Date;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 08 17:57:54 PKT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvItemImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        ItemId,
        ItemShortCode,
        ItemShortName,
        Description,
        MaxLevel,
        MinLevel,
        ReorderQty,
        UnitTypeSno,
        PurchaseUnitTypeSno,
        SaleUnitTypeSno,
        StockUnitTypeSno,
        IsActive,
        CreatedBy,
        CreatedDate,
        LastUpdateBy,
        LastUpdateDate,
        IsTaxable,
        TaxGroupSno,
        Qty,
        CompanyId,
        ItemPictureName,
        CostingMethodSno,
        CoaCostOfGoodsSold,
        CoaBillPriceVariance,
        CoaGainLoss,
        CoaAsset,
        CoaQuantityAdjustment,
        CoaPurchasePriceVariance,
        CoaSaleReturnVariance,
        CoaWip,
        CoaInventory,
        CoaPurchaseReturnVariance,
        CoaExchangeRate,
        CoaShipment,
        CoaIncome,
        IsSupervised,
        SupervisedDate,
        IsUnsupervised,
        UnSupervisedDate,
        SupervisedBy,
        UnSupervisedBy,
        EndDate,
        StartDate,
        txtCOACOGSDescription,
        txtCoaBillPriceVarDescription,
        txtCoaExRateVarDescription,
        txtQuantityAdjustDescription,
        txtCoaWipDescription,
        txtCOAIncomeDescription,
        GlChartOfAccounts,
        GlChartOfAccounts1,
        GlChartOfAccounts2,
        GlChartOfAccounts3,
        GlChartOfAccounts4,
        GlChartOfAccounts5;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int ITEMSHORTCODE = AttributesEnum.ItemShortCode.index();
    public static final int ITEMSHORTNAME = AttributesEnum.ItemShortName.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int MAXLEVEL = AttributesEnum.MaxLevel.index();
    public static final int MINLEVEL = AttributesEnum.MinLevel.index();
    public static final int REORDERQTY = AttributesEnum.ReorderQty.index();
    public static final int UNITTYPESNO = AttributesEnum.UnitTypeSno.index();
    public static final int PURCHASEUNITTYPESNO = AttributesEnum.PurchaseUnitTypeSno.index();
    public static final int SALEUNITTYPESNO = AttributesEnum.SaleUnitTypeSno.index();
    public static final int STOCKUNITTYPESNO = AttributesEnum.StockUnitTypeSno.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEBY = AttributesEnum.LastUpdateBy.index();
    public static final int LASTUPDATEDATE = AttributesEnum.LastUpdateDate.index();
    public static final int ISTAXABLE = AttributesEnum.IsTaxable.index();
    public static final int TAXGROUPSNO = AttributesEnum.TaxGroupSno.index();
    public static final int QTY = AttributesEnum.Qty.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int ITEMPICTURENAME = AttributesEnum.ItemPictureName.index();
    public static final int COSTINGMETHODSNO = AttributesEnum.CostingMethodSno.index();
    public static final int COACOSTOFGOODSSOLD = AttributesEnum.CoaCostOfGoodsSold.index();
    public static final int COABILLPRICEVARIANCE = AttributesEnum.CoaBillPriceVariance.index();
    public static final int COAGAINLOSS = AttributesEnum.CoaGainLoss.index();
    public static final int COAASSET = AttributesEnum.CoaAsset.index();
    public static final int COAQUANTITYADJUSTMENT = AttributesEnum.CoaQuantityAdjustment.index();
    public static final int COAPURCHASEPRICEVARIANCE = AttributesEnum.CoaPurchasePriceVariance.index();
    public static final int COASALERETURNVARIANCE = AttributesEnum.CoaSaleReturnVariance.index();
    public static final int COAWIP = AttributesEnum.CoaWip.index();
    public static final int COAINVENTORY = AttributesEnum.CoaInventory.index();
    public static final int COAPURCHASERETURNVARIANCE = AttributesEnum.CoaPurchaseReturnVariance.index();
    public static final int COAEXCHANGERATE = AttributesEnum.CoaExchangeRate.index();
    public static final int COASHIPMENT = AttributesEnum.CoaShipment.index();
    public static final int COAINCOME = AttributesEnum.CoaIncome.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int TXTCOACOGSDESCRIPTION = AttributesEnum.txtCOACOGSDescription.index();
    public static final int TXTCOABILLPRICEVARDESCRIPTION = AttributesEnum.txtCoaBillPriceVarDescription.index();
    public static final int TXTCOAEXRATEVARDESCRIPTION = AttributesEnum.txtCoaExRateVarDescription.index();
    public static final int TXTQUANTITYADJUSTDESCRIPTION = AttributesEnum.txtQuantityAdjustDescription.index();
    public static final int TXTCOAWIPDESCRIPTION = AttributesEnum.txtCoaWipDescription.index();
    public static final int TXTCOAINCOMEDESCRIPTION = AttributesEnum.txtCOAIncomeDescription.index();
    public static final int GLCHARTOFACCOUNTS = AttributesEnum.GlChartOfAccounts.index();
    public static final int GLCHARTOFACCOUNTS1 = AttributesEnum.GlChartOfAccounts1.index();
    public static final int GLCHARTOFACCOUNTS2 = AttributesEnum.GlChartOfAccounts2.index();
    public static final int GLCHARTOFACCOUNTS3 = AttributesEnum.GlChartOfAccounts3.index();
    public static final int GLCHARTOFACCOUNTS4 = AttributesEnum.GlChartOfAccounts4.index();
    public static final int GLCHARTOFACCOUNTS5 = AttributesEnum.GlChartOfAccounts5.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvItemImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpims.modelims.imseo.InvItem");
    }


    /**
     * Gets the attribute value for ItemId, using the alias name ItemId.
     * @return the value of ItemId
     */
    public Integer getItemId() {
        return (Integer) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemId.
     * @param value value to set the ItemId
     */
    public void setItemId(Integer value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for ItemShortCode, using the alias name ItemShortCode.
     * @return the value of ItemShortCode
     */
    public Integer getItemShortCode() {
        return (Integer) getAttributeInternal(ITEMSHORTCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemShortCode.
     * @param value value to set the ItemShortCode
     */
    public void setItemShortCode(Integer value) {
        setAttributeInternal(ITEMSHORTCODE, value);
    }

    /**
     * Gets the attribute value for ItemShortName, using the alias name ItemShortName.
     * @return the value of ItemShortName
     */
    public String getItemShortName() {
        return (String) getAttributeInternal(ITEMSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemShortName.
     * @param value value to set the ItemShortName
     */
    public void setItemShortName(String value) {
        setAttributeInternal(ITEMSHORTNAME, value);
    }

    /**
     * Gets the attribute value for Description, using the alias name Description.
     * @return the value of Description
     */
    public String getDescription() {
        return (String) getAttributeInternal(DESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for Description.
     * @param value value to set the Description
     */
    public void setDescription(String value) {
        setAttributeInternal(DESCRIPTION, value);
    }

    /**
     * Gets the attribute value for MaxLevel, using the alias name MaxLevel.
     * @return the value of MaxLevel
     */
    public BigDecimal getMaxLevel() {
        return (BigDecimal) getAttributeInternal(MAXLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for MaxLevel.
     * @param value value to set the MaxLevel
     */
    public void setMaxLevel(BigDecimal value) {
        setAttributeInternal(MAXLEVEL, value);
    }

    /**
     * Gets the attribute value for MinLevel, using the alias name MinLevel.
     * @return the value of MinLevel
     */
    public BigDecimal getMinLevel() {
        return (BigDecimal) getAttributeInternal(MINLEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for MinLevel.
     * @param value value to set the MinLevel
     */
    public void setMinLevel(BigDecimal value) {
        setAttributeInternal(MINLEVEL, value);
    }

    /**
     * Gets the attribute value for ReorderQty, using the alias name ReorderQty.
     * @return the value of ReorderQty
     */
    public BigDecimal getReorderQty() {
        return (BigDecimal) getAttributeInternal(REORDERQTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for ReorderQty.
     * @param value value to set the ReorderQty
     */
    public void setReorderQty(BigDecimal value) {
        setAttributeInternal(REORDERQTY, value);
    }

    /**
     * Gets the attribute value for UnitTypeSno, using the alias name UnitTypeSno.
     * @return the value of UnitTypeSno
     */
    public Integer getUnitTypeSno() {
        return (Integer) getAttributeInternal(UNITTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnitTypeSno.
     * @param value value to set the UnitTypeSno
     */
    public void setUnitTypeSno(Integer value) {
        setAttributeInternal(UNITTYPESNO, value);
    }

    /**
     * Gets the attribute value for PurchaseUnitTypeSno, using the alias name PurchaseUnitTypeSno.
     * @return the value of PurchaseUnitTypeSno
     */
    public Integer getPurchaseUnitTypeSno() {
        return (Integer) getAttributeInternal(PURCHASEUNITTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PurchaseUnitTypeSno.
     * @param value value to set the PurchaseUnitTypeSno
     */
    public void setPurchaseUnitTypeSno(Integer value) {
        setAttributeInternal(PURCHASEUNITTYPESNO, value);
    }

    /**
     * Gets the attribute value for SaleUnitTypeSno, using the alias name SaleUnitTypeSno.
     * @return the value of SaleUnitTypeSno
     */
    public Integer getSaleUnitTypeSno() {
        return (Integer) getAttributeInternal(SALEUNITTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for SaleUnitTypeSno.
     * @param value value to set the SaleUnitTypeSno
     */
    public void setSaleUnitTypeSno(Integer value) {
        setAttributeInternal(SALEUNITTYPESNO, value);
    }

    /**
     * Gets the attribute value for StockUnitTypeSno, using the alias name StockUnitTypeSno.
     * @return the value of StockUnitTypeSno
     */
    public Integer getStockUnitTypeSno() {
        return (Integer) getAttributeInternal(STOCKUNITTYPESNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StockUnitTypeSno.
     * @param value value to set the StockUnitTypeSno
     */
    public void setStockUnitTypeSno(Integer value) {
        setAttributeInternal(STOCKUNITTYPESNO, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdateBy, using the alias name LastUpdateBy.
     * @return the value of LastUpdateBy
     */
    public Integer getLastUpdateBy() {
        return (Integer) getAttributeInternal(LASTUPDATEBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateBy.
     * @param value value to set the LastUpdateBy
     */
    public void setLastUpdateBy(Integer value) {
        setAttributeInternal(LASTUPDATEBY, value);
    }

    /**
     * Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate.
     * @return the value of LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date) getAttributeInternal(LASTUPDATEDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdateDate.
     * @param value value to set the LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**
     * Gets the attribute value for IsTaxable, using the alias name IsTaxable.
     * @return the value of IsTaxable
     */
    public String getIsTaxable() {
        return (String) getAttributeInternal(ISTAXABLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsTaxable.
     * @param value value to set the IsTaxable
     */
    public void setIsTaxable(String value) {
        setAttributeInternal(ISTAXABLE, value);
    }

    /**
     * Gets the attribute value for TaxGroupSno, using the alias name TaxGroupSno.
     * @return the value of TaxGroupSno
     */
    public Integer getTaxGroupSno() {
        return (Integer) getAttributeInternal(TAXGROUPSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxGroupSno.
     * @param value value to set the TaxGroupSno
     */
    public void setTaxGroupSno(Integer value) {
        setAttributeInternal(TAXGROUPSNO, value);
    }

    /**
     * Gets the attribute value for Qty, using the alias name Qty.
     * @return the value of Qty
     */
    public BigDecimal getQty() {
        return (BigDecimal) getAttributeInternal(QTY);
    }

    /**
     * Sets <code>value</code> as the attribute value for Qty.
     * @param value value to set the Qty
     */
    public void setQty(BigDecimal value) {
        setAttributeInternal(QTY, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for ItemPictureName, using the alias name ItemPictureName.
     * @return the value of ItemPictureName
     */
    public String getItemPictureName() {
        return (String) getAttributeInternal(ITEMPICTURENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for ItemPictureName.
     * @param value value to set the ItemPictureName
     */
    public void setItemPictureName(String value) {
        setAttributeInternal(ITEMPICTURENAME, value);
    }

    /**
     * Gets the attribute value for CostingMethodSno, using the alias name CostingMethodSno.
     * @return the value of CostingMethodSno
     */
    public Integer getCostingMethodSno() {
        return (Integer) getAttributeInternal(COSTINGMETHODSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CostingMethodSno.
     * @param value value to set the CostingMethodSno
     */
    public void setCostingMethodSno(Integer value) {
        setAttributeInternal(COSTINGMETHODSNO, value);
    }

    /**
     * Gets the attribute value for CoaCostOfGoodsSold, using the alias name CoaCostOfGoodsSold.
     * @return the value of CoaCostOfGoodsSold
     */
    public BigDecimal getCoaCostOfGoodsSold() {
        return (BigDecimal) getAttributeInternal(COACOSTOFGOODSSOLD);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaCostOfGoodsSold.
     * @param value value to set the CoaCostOfGoodsSold
     */
    public void setCoaCostOfGoodsSold(BigDecimal value) {
        setAttributeInternal(COACOSTOFGOODSSOLD, value);
    }

    /**
     * Gets the attribute value for CoaBillPriceVariance, using the alias name CoaBillPriceVariance.
     * @return the value of CoaBillPriceVariance
     */
    public BigDecimal getCoaBillPriceVariance() {
        return (BigDecimal) getAttributeInternal(COABILLPRICEVARIANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaBillPriceVariance.
     * @param value value to set the CoaBillPriceVariance
     */
    public void setCoaBillPriceVariance(BigDecimal value) {
        setAttributeInternal(COABILLPRICEVARIANCE, value);
    }

    /**
     * Gets the attribute value for CoaGainLoss, using the alias name CoaGainLoss.
     * @return the value of CoaGainLoss
     */
    public Integer getCoaGainLoss() {
        return (Integer) getAttributeInternal(COAGAINLOSS);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaGainLoss.
     * @param value value to set the CoaGainLoss
     */
    public void setCoaGainLoss(Integer value) {
        setAttributeInternal(COAGAINLOSS, value);
    }

    /**
     * Gets the attribute value for CoaAsset, using the alias name CoaAsset.
     * @return the value of CoaAsset
     */
    public Integer getCoaAsset() {
        return (Integer) getAttributeInternal(COAASSET);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaAsset.
     * @param value value to set the CoaAsset
     */
    public void setCoaAsset(Integer value) {
        setAttributeInternal(COAASSET, value);
    }

    /**
     * Gets the attribute value for CoaQuantityAdjustment, using the alias name CoaQuantityAdjustment.
     * @return the value of CoaQuantityAdjustment
     */
    public Integer getCoaQuantityAdjustment() {
        return (Integer) getAttributeInternal(COAQUANTITYADJUSTMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaQuantityAdjustment.
     * @param value value to set the CoaQuantityAdjustment
     */
    public void setCoaQuantityAdjustment(Integer value) {
        setAttributeInternal(COAQUANTITYADJUSTMENT, value);
    }

    /**
     * Gets the attribute value for CoaPurchasePriceVariance, using the alias name CoaPurchasePriceVariance.
     * @return the value of CoaPurchasePriceVariance
     */
    public Integer getCoaPurchasePriceVariance() {
        return (Integer) getAttributeInternal(COAPURCHASEPRICEVARIANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaPurchasePriceVariance.
     * @param value value to set the CoaPurchasePriceVariance
     */
    public void setCoaPurchasePriceVariance(Integer value) {
        setAttributeInternal(COAPURCHASEPRICEVARIANCE, value);
    }

    /**
     * Gets the attribute value for CoaSaleReturnVariance, using the alias name CoaSaleReturnVariance.
     * @return the value of CoaSaleReturnVariance
     */
    public Integer getCoaSaleReturnVariance() {
        return (Integer) getAttributeInternal(COASALERETURNVARIANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaSaleReturnVariance.
     * @param value value to set the CoaSaleReturnVariance
     */
    public void setCoaSaleReturnVariance(Integer value) {
        setAttributeInternal(COASALERETURNVARIANCE, value);
    }

    /**
     * Gets the attribute value for CoaWip, using the alias name CoaWip.
     * @return the value of CoaWip
     */
    public Integer getCoaWip() {
        return (Integer) getAttributeInternal(COAWIP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaWip.
     * @param value value to set the CoaWip
     */
    public void setCoaWip(Integer value) {
        setAttributeInternal(COAWIP, value);
    }

    /**
     * Gets the attribute value for CoaInventory, using the alias name CoaInventory.
     * @return the value of CoaInventory
     */
    public Integer getCoaInventory() {
        return (Integer) getAttributeInternal(COAINVENTORY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaInventory.
     * @param value value to set the CoaInventory
     */
    public void setCoaInventory(Integer value) {
        setAttributeInternal(COAINVENTORY, value);
    }

    /**
     * Gets the attribute value for CoaPurchaseReturnVariance, using the alias name CoaPurchaseReturnVariance.
     * @return the value of CoaPurchaseReturnVariance
     */
    public Integer getCoaPurchaseReturnVariance() {
        return (Integer) getAttributeInternal(COAPURCHASERETURNVARIANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaPurchaseReturnVariance.
     * @param value value to set the CoaPurchaseReturnVariance
     */
    public void setCoaPurchaseReturnVariance(Integer value) {
        setAttributeInternal(COAPURCHASERETURNVARIANCE, value);
    }

    /**
     * Gets the attribute value for CoaExchangeRate, using the alias name CoaExchangeRate.
     * @return the value of CoaExchangeRate
     */
    public Integer getCoaExchangeRate() {
        return (Integer) getAttributeInternal(COAEXCHANGERATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaExchangeRate.
     * @param value value to set the CoaExchangeRate
     */
    public void setCoaExchangeRate(Integer value) {
        setAttributeInternal(COAEXCHANGERATE, value);
    }

    /**
     * Gets the attribute value for CoaShipment, using the alias name CoaShipment.
     * @return the value of CoaShipment
     */
    public Integer getCoaShipment() {
        return (Integer) getAttributeInternal(COASHIPMENT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaShipment.
     * @param value value to set the CoaShipment
     */
    public void setCoaShipment(Integer value) {
        setAttributeInternal(COASHIPMENT, value);
    }

    /**
     * Gets the attribute value for CoaIncome, using the alias name CoaIncome.
     * @return the value of CoaIncome
     */
    public Integer getCoaIncome() {
        return (Integer) getAttributeInternal(COAINCOME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CoaIncome.
     * @param value value to set the CoaIncome
     */
    public void setCoaIncome(Integer value) {
        setAttributeInternal(COAINCOME, value);
    }

    /**
     * Gets the attribute value for IsSupervised, using the alias name IsSupervised.
     * @return the value of IsSupervised
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSupervised.
     * @param value value to set the IsSupervised
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for SupervisedDate, using the alias name SupervisedDate.
     * @return the value of SupervisedDate
     */
    public Date getSupervisedDate() {
        return (Date) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedDate.
     * @param value value to set the SupervisedDate
     */
    public void setSupervisedDate(Date value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IsUnsupervised, using the alias name IsUnsupervised.
     * @return the value of IsUnsupervised
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsUnsupervised.
     * @param value value to set the IsUnsupervised
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UnSupervisedDate, using the alias name UnSupervisedDate.
     * @return the value of UnSupervisedDate
     */
    public Date getUnSupervisedDate() {
        return (Date) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedDate.
     * @param value value to set the UnSupervisedDate
     */
    public void setUnSupervisedDate(Date value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for SupervisedBy, using the alias name SupervisedBy.
     * @return the value of SupervisedBy
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedBy.
     * @param value value to set the SupervisedBy
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UnSupervisedBy, using the alias name UnSupervisedBy.
     * @return the value of UnSupervisedBy
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedBy.
     * @param value value to set the UnSupervisedBy
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the value of EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * Gets the attribute value for txtCOACOGSDescription, using the alias name txtCOACOGSDescription.
     * @return the value of txtCOACOGSDescription
     */
    public String gettxtCOACOGSDescription() {
        return (String) getAttributeInternal(TXTCOACOGSDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCOACOGSDescription.
     * @param value value to set the txtCOACOGSDescription
     */
    public void settxtCOACOGSDescription(String value) {
        setAttributeInternal(TXTCOACOGSDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for txtCoaBillPriceVarDescription, using the alias name txtCoaBillPriceVarDescription.
     * @return the value of txtCoaBillPriceVarDescription
     */
    public String gettxtCoaBillPriceVarDescription() {
        return (String) getAttributeInternal(TXTCOABILLPRICEVARDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCoaBillPriceVarDescription.
     * @param value value to set the txtCoaBillPriceVarDescription
     */
    public void settxtCoaBillPriceVarDescription(String value) {
        setAttributeInternal(TXTCOABILLPRICEVARDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for txtCoaExRateVarDescription, using the alias name txtCoaExRateVarDescription.
     * @return the value of txtCoaExRateVarDescription
     */
    public String gettxtCoaExRateVarDescription() {
        return (String) getAttributeInternal(TXTCOAEXRATEVARDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCoaExRateVarDescription.
     * @param value value to set the txtCoaExRateVarDescription
     */
    public void settxtCoaExRateVarDescription(String value) {
        setAttributeInternal(TXTCOAEXRATEVARDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for txtQuantityAdjustDescription, using the alias name txtQuantityAdjustDescription.
     * @return the value of txtQuantityAdjustDescription
     */
    public String gettxtQuantityAdjustDescription() {
        return (String) getAttributeInternal(TXTQUANTITYADJUSTDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtQuantityAdjustDescription.
     * @param value value to set the txtQuantityAdjustDescription
     */
    public void settxtQuantityAdjustDescription(String value) {
        setAttributeInternal(TXTQUANTITYADJUSTDESCRIPTION, value);
    }


    /**
     * Gets the attribute value for txtCoaWipDescription, using the alias name txtCoaWipDescription.
     * @return the value of txtCoaWipDescription
     */
    public String gettxtCoaWipDescription() {
        return (String) getAttributeInternal(TXTCOAWIPDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCoaWipDescription.
     * @param value value to set the txtCoaWipDescription
     */
    public void settxtCoaWipDescription(String value) {
        setAttributeInternal(TXTCOAWIPDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for txtCOAIncomeDescription, using the alias name txtCOAIncomeDescription.
     * @return the value of txtCOAIncomeDescription
     */
    public String gettxtCOAIncomeDescription() {
        return (String) getAttributeInternal(TXTCOAINCOMEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCOAIncomeDescription.
     * @param value value to set the txtCOAIncomeDescription
     */
    public void settxtCOAIncomeDescription(String value) {
        setAttributeInternal(TXTCOAINCOMEDESCRIPTION, value);
    }

    /**
     * @return the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public GlChartOfAccountsImpl getGlChartOfAccounts() {
        return (GlChartOfAccountsImpl) getAttributeInternal(GLCHARTOFACCOUNTS);
    }

    /**
     * Sets <code>value</code> as the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public void setGlChartOfAccounts(GlChartOfAccountsImpl value) {
        setAttributeInternal(GLCHARTOFACCOUNTS, value);
    }


    /**
     * @return the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public GlChartOfAccountsImpl getGlChartOfAccounts1() {
        return (GlChartOfAccountsImpl) getAttributeInternal(GLCHARTOFACCOUNTS1);
    }

    /**
     * Sets <code>value</code> as the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public void setGlChartOfAccounts1(GlChartOfAccountsImpl value) {
        setAttributeInternal(GLCHARTOFACCOUNTS1, value);
    }


    /**
     * @return the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public GlChartOfAccountsImpl getGlChartOfAccounts2() {
        return (GlChartOfAccountsImpl) getAttributeInternal(GLCHARTOFACCOUNTS2);
    }

    /**
     * Sets <code>value</code> as the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public void setGlChartOfAccounts2(GlChartOfAccountsImpl value) {
        setAttributeInternal(GLCHARTOFACCOUNTS2, value);
    }


    /**
     * @return the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public GlChartOfAccountsImpl getGlChartOfAccounts3() {
        return (GlChartOfAccountsImpl) getAttributeInternal(GLCHARTOFACCOUNTS3);
    }

    /**
     * Sets <code>value</code> as the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public void setGlChartOfAccounts3(GlChartOfAccountsImpl value) {
        setAttributeInternal(GLCHARTOFACCOUNTS3, value);
    }


    /**
     * @return the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public GlChartOfAccountsImpl getGlChartOfAccounts4() {
        return (GlChartOfAccountsImpl) getAttributeInternal(GLCHARTOFACCOUNTS4);
    }

    /**
     * Sets <code>value</code> as the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public void setGlChartOfAccounts4(GlChartOfAccountsImpl value) {
        setAttributeInternal(GLCHARTOFACCOUNTS4, value);
    }


    /**
     * @return the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public GlChartOfAccountsImpl getGlChartOfAccounts5() {
        return (GlChartOfAccountsImpl) getAttributeInternal(GLCHARTOFACCOUNTS5);
    }

    /**
     * Sets <code>value</code> as the associated entity erpfms.modelfms.fmseo.GlChartOfAccountsImpl.
     */
    public void setGlChartOfAccounts5(GlChartOfAccountsImpl value) {
        setAttributeInternal(GLCHARTOFACCOUNTS5, value);
    }


    /**
     * @param itemId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer itemId) {
        return new Key(new Object[] { itemId });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }
}

