package erpims.modelims.imseo;

import erpadm.modeladm.admeo.AdminCompanyImpl;
import erpadm.modeladm.admeo.SmCityImpl;
import erpadm.modeladm.admeo.SmCountryImpl;

import erpglobals.modelglobals.ERPEntityImpl;

import erpglobals.modelglobals.ERPGlobalPLSQLClass;

import java.sql.Date;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 20 22:35:24 PKT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvInventoryOrgImpl extends ERPEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        InventoryOrgSno,
        InventoryOrgCode,
        OrgShortName,
        OrgDescription,
        OpenDate,
        ParentInventoryOrgSno,
        LocationId,
        CompanyId,
        GlobalCompanyId,
        IsActive,
        CountrySno,
        CitySno,
        Address,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        IsSupervised,
        SupervisedDate,
        IsUnsupervised,
        UnSupervisedDate,
        SupervisedBy,
        UnSupervisedBy,
        PhoneNo,
        FaxNo,
        MobileNo,
        ContactPerson,
        txtLocationName,
        txtParentOrgName,
        txtCountryName,
        txtCityName,
        EndDate,
        OrgHierarchyPath,
        StartDate,
        AdminCompany,
        InvInventoryOrg,
        ParentInventoryOrgSnoInvInventoryOrg,
        SmCountry,
        SmCity;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int INVENTORYORGSNO = AttributesEnum.InventoryOrgSno.index();
    public static final int INVENTORYORGCODE = AttributesEnum.InventoryOrgCode.index();
    public static final int ORGSHORTNAME = AttributesEnum.OrgShortName.index();
    public static final int ORGDESCRIPTION = AttributesEnum.OrgDescription.index();
    public static final int OPENDATE = AttributesEnum.OpenDate.index();
    public static final int PARENTINVENTORYORGSNO = AttributesEnum.ParentInventoryOrgSno.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int ISACTIVE = AttributesEnum.IsActive.index();
    public static final int COUNTRYSNO = AttributesEnum.CountrySno.index();
    public static final int CITYSNO = AttributesEnum.CitySno.index();
    public static final int ADDRESS = AttributesEnum.Address.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int PHONENO = AttributesEnum.PhoneNo.index();
    public static final int FAXNO = AttributesEnum.FaxNo.index();
    public static final int MOBILENO = AttributesEnum.MobileNo.index();
    public static final int CONTACTPERSON = AttributesEnum.ContactPerson.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTPARENTORGNAME = AttributesEnum.txtParentOrgName.index();
    public static final int TXTCOUNTRYNAME = AttributesEnum.txtCountryName.index();
    public static final int TXTCITYNAME = AttributesEnum.txtCityName.index();
    public static final int ENDDATE = AttributesEnum.EndDate.index();
    public static final int ORGHIERARCHYPATH = AttributesEnum.OrgHierarchyPath.index();
    public static final int STARTDATE = AttributesEnum.StartDate.index();
    public static final int ADMINCOMPANY = AttributesEnum.AdminCompany.index();
    public static final int INVINVENTORYORG = AttributesEnum.InvInventoryOrg.index();
    public static final int PARENTINVENTORYORGSNOINVINVENTORYORG =
        AttributesEnum.ParentInventoryOrgSnoInvInventoryOrg.index();
    public static final int SMCOUNTRY = AttributesEnum.SmCountry.index();
    public static final int SMCITY = AttributesEnum.SmCity.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvInventoryOrgImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("erpims.modelims.imseo.InvInventoryOrg");
    }


    /**
     * Gets the attribute value for InventoryOrgSno, using the alias name InventoryOrgSno.
     * @return the value of InventoryOrgSno
     */
    public Integer getInventoryOrgSno() {
        return (Integer) getAttributeInternal(INVENTORYORGSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryOrgSno.
     * @param value value to set the InventoryOrgSno
     */
    public void setInventoryOrgSno(Integer value) {
        setAttributeInternal(INVENTORYORGSNO, value);
    }

    /**
     * Gets the attribute value for InventoryOrgCode, using the alias name InventoryOrgCode.
     * @return the value of InventoryOrgCode
     */
    public Integer getInventoryOrgCode() {
        return (Integer) getAttributeInternal(INVENTORYORGCODE);
    }

    /**
     * Sets <code>value</code> as the attribute value for InventoryOrgCode.
     * @param value value to set the InventoryOrgCode
     */
    public void setInventoryOrgCode(Integer value) {
        setAttributeInternal(INVENTORYORGCODE, value);
    }

    /**
     * Gets the attribute value for OrgShortName, using the alias name OrgShortName.
     * @return the value of OrgShortName
     */
    public String getOrgShortName() {
        return (String) getAttributeInternal(ORGSHORTNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgShortName.
     * @param value value to set the OrgShortName
     */
    public void setOrgShortName(String value) {
        setAttributeInternal(ORGSHORTNAME, value);
    }

    /**
     * Gets the attribute value for OrgDescription, using the alias name OrgDescription.
     * @return the value of OrgDescription
     */
    public String getOrgDescription() {
        return (String) getAttributeInternal(ORGDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgDescription.
     * @param value value to set the OrgDescription
     */
    public void setOrgDescription(String value) {
        setAttributeInternal(ORGDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for OpenDate, using the alias name OpenDate.
     * @return the value of OpenDate
     */
    public Date getOpenDate() {
        return (Date) getAttributeInternal(OPENDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for OpenDate.
     * @param value value to set the OpenDate
     */
    public void setOpenDate(Date value) {
        setAttributeInternal(OPENDATE, value);
    }

    /**
     * Gets the attribute value for ParentInventoryOrgSno, using the alias name ParentInventoryOrgSno.
     * @return the value of ParentInventoryOrgSno
     */
    public Integer getParentInventoryOrgSno() {
        return (Integer) getAttributeInternal(PARENTINVENTORYORGSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for ParentInventoryOrgSno.
     * @param value value to set the ParentInventoryOrgSno
     */
    public void setParentInventoryOrgSno(Integer value) {
        setAttributeInternal(PARENTINVENTORYORGSNO, value);
    }

    /**
     * Gets the attribute value for LocationId, using the alias name LocationId.
     * @return the value of LocationId
     */
    public Integer getLocationId() {
        return (Integer) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for LocationId.
     * @param value value to set the LocationId
     */
    public void setLocationId(Integer value) {
        setAttributeInternal(LOCATIONID, value);
    }

    /**
     * Gets the attribute value for CompanyId, using the alias name CompanyId.
     * @return the value of CompanyId
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CompanyId.
     * @param value value to set the CompanyId
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for GlobalCompanyId, using the alias name GlobalCompanyId.
     * @return the value of GlobalCompanyId
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for GlobalCompanyId.
     * @param value value to set the GlobalCompanyId
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for IsActive, using the alias name IsActive.
     * @return the value of IsActive
     */
    public String getIsActive() {
        return (String) getAttributeInternal(ISACTIVE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsActive.
     * @param value value to set the IsActive
     */
    public void setIsActive(String value) {
        setAttributeInternal(ISACTIVE, value);
    }

    /**
     * Gets the attribute value for CountrySno, using the alias name CountrySno.
     * @return the value of CountrySno
     */
    public Integer getCountrySno() {
        return (Integer) getAttributeInternal(COUNTRYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CountrySno.
     * @param value value to set the CountrySno
     */
    public void setCountrySno(Integer value) {
        setAttributeInternal(COUNTRYSNO, value);
    }

    /**
     * Gets the attribute value for CitySno, using the alias name CitySno.
     * @return the value of CitySno
     */
    public Integer getCitySno() {
        return (Integer) getAttributeInternal(CITYSNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for CitySno.
     * @param value value to set the CitySno
     */
    public void setCitySno(Integer value) {
        setAttributeInternal(CITYSNO, value);
    }

    /**
     * Gets the attribute value for Address, using the alias name Address.
     * @return the value of Address
     */
    public String getAddress() {
        return (String) getAttributeInternal(ADDRESS);
    }

    /**
     * Sets <code>value</code> as the attribute value for Address.
     * @param value value to set the Address
     */
    public void setAddress(String value) {
        setAttributeInternal(ADDRESS, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the value of CreatedBy
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedDate, using the alias name CreatedDate.
     * @return the value of CreatedDate
     */
    public Date getCreatedDate() {
        return (Date) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedDate.
     * @param value value to set the CreatedDate
     */
    public void setCreatedDate(Date value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy.
     * @return the value of LastUpdatedBy
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedBy.
     * @param value value to set the LastUpdatedBy
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LastUpdatedDate, using the alias name LastUpdatedDate.
     * @return the value of LastUpdatedDate
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastUpdatedDate.
     * @param value value to set the LastUpdatedDate
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IsSupervised, using the alias name IsSupervised.
     * @return the value of IsSupervised
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsSupervised.
     * @param value value to set the IsSupervised
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for SupervisedDate, using the alias name SupervisedDate.
     * @return the value of SupervisedDate
     */
    public Date getSupervisedDate() {
        return (Date) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedDate.
     * @param value value to set the SupervisedDate
     */
    public void setSupervisedDate(Date value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IsUnsupervised, using the alias name IsUnsupervised.
     * @return the value of IsUnsupervised
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsUnsupervised.
     * @param value value to set the IsUnsupervised
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UnSupervisedDate, using the alias name UnSupervisedDate.
     * @return the value of UnSupervisedDate
     */
    public Date getUnSupervisedDate() {
        return (Date) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedDate.
     * @param value value to set the UnSupervisedDate
     */
    public void setUnSupervisedDate(Date value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for SupervisedBy, using the alias name SupervisedBy.
     * @return the value of SupervisedBy
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for SupervisedBy.
     * @param value value to set the SupervisedBy
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UnSupervisedBy, using the alias name UnSupervisedBy.
     * @return the value of UnSupervisedBy
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UnSupervisedBy.
     * @param value value to set the UnSupervisedBy
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for PhoneNo, using the alias name PhoneNo.
     * @return the value of PhoneNo
     */
    public String getPhoneNo() {
        return (String) getAttributeInternal(PHONENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for PhoneNo.
     * @param value value to set the PhoneNo
     */
    public void setPhoneNo(String value) {
        setAttributeInternal(PHONENO, value);
    }

    /**
     * Gets the attribute value for FaxNo, using the alias name FaxNo.
     * @return the value of FaxNo
     */
    public String getFaxNo() {
        return (String) getAttributeInternal(FAXNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for FaxNo.
     * @param value value to set the FaxNo
     */
    public void setFaxNo(String value) {
        setAttributeInternal(FAXNO, value);
    }

    /**
     * Gets the attribute value for MobileNo, using the alias name MobileNo.
     * @return the value of MobileNo
     */
    public String getMobileNo() {
        return (String) getAttributeInternal(MOBILENO);
    }

    /**
     * Sets <code>value</code> as the attribute value for MobileNo.
     * @param value value to set the MobileNo
     */
    public void setMobileNo(String value) {
        setAttributeInternal(MOBILENO, value);
    }

    /**
     * Gets the attribute value for ContactPerson, using the alias name ContactPerson.
     * @return the value of ContactPerson
     */
    public String getContactPerson() {
        return (String) getAttributeInternal(CONTACTPERSON);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContactPerson.
     * @param value value to set the ContactPerson
     */
    public void setContactPerson(String value) {
        setAttributeInternal(CONTACTPERSON, value);
    }

    /**
     * Gets the attribute value for txtLocationName, using the alias name txtLocationName.
     * @return the value of txtLocationName
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtLocationName.
     * @param value value to set the txtLocationName
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for txtParentOrgName, using the alias name txtParentOrgName.
     * @return the value of txtParentOrgName
     */
    public String gettxtParentOrgName() {
        return (String) getAttributeInternal(TXTPARENTORGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtParentOrgName.
     * @param value value to set the txtParentOrgName
     */
    public void settxtParentOrgName(String value) {
        setAttributeInternal(TXTPARENTORGNAME, value);
    }

    /**
     * Gets the attribute value for txtCountryName, using the alias name txtCountryName.
     * @return the value of txtCountryName
     */
    public String gettxtCountryName() {
        return (String) getAttributeInternal(TXTCOUNTRYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCountryName.
     * @param value value to set the txtCountryName
     */
    public void settxtCountryName(String value) {
        setAttributeInternal(TXTCOUNTRYNAME, value);
    }

    /**
     * Gets the attribute value for txtCityName, using the alias name txtCityName.
     * @return the value of txtCityName
     */
    public String gettxtCityName() {
        return (String) getAttributeInternal(TXTCITYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for txtCityName.
     * @param value value to set the txtCityName
     */
    public void settxtCityName(String value) {
        setAttributeInternal(TXTCITYNAME, value);
    }

    /**
     * Gets the attribute value for EndDate, using the alias name EndDate.
     * @return the value of EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for EndDate.
     * @param value value to set the EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**
     * Gets the attribute value for OrgHierarchyPath, using the alias name OrgHierarchyPath.
     * @return the value of OrgHierarchyPath
     */
    public String getOrgHierarchyPath() {
        return (String) getAttributeInternal(ORGHIERARCHYPATH);
    }

    /**
     * Sets <code>value</code> as the attribute value for OrgHierarchyPath.
     * @param value value to set the OrgHierarchyPath
     */
    public void setOrgHierarchyPath(String value) {
        setAttributeInternal(ORGHIERARCHYPATH, value);
    }

    /**
     * Gets the attribute value for StartDate, using the alias name StartDate.
     * @return the value of StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for StartDate.
     * @param value value to set the StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**
     * @return the associated entity erpadm.modeladm.admeo.AdminCompanyImpl.
     */
    public AdminCompanyImpl getAdminCompany() {
        return (AdminCompanyImpl) getAttributeInternal(ADMINCOMPANY);
    }

    /**
     * Sets <code>value</code> as the associated entity erpadm.modeladm.admeo.AdminCompanyImpl.
     */
    public void setAdminCompany(AdminCompanyImpl value) {
        setAttributeInternal(ADMINCOMPANY, value);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getInvInventoryOrg() {
        return (RowIterator) getAttributeInternal(INVINVENTORYORG);
    }

    /**
     * @return the associated entity InvInventoryOrgImpl.
     */
    public InvInventoryOrgImpl getParentInventoryOrgSnoInvInventoryOrg() {
        return (InvInventoryOrgImpl) getAttributeInternal(PARENTINVENTORYORGSNOINVINVENTORYORG);
    }

    /**
     * Sets <code>value</code> as the associated entity InvInventoryOrgImpl.
     */
    public void setParentInventoryOrgSnoInvInventoryOrg(InvInventoryOrgImpl value) {
        setAttributeInternal(PARENTINVENTORYORGSNOINVINVENTORYORG, value);
    }

    /**
     * @return the associated entity erpadm.modeladm.admeo.SmCountryImpl.
     */
    public SmCountryImpl getSmCountry() {
        return (SmCountryImpl) getAttributeInternal(SMCOUNTRY);
    }

    /**
     * Sets <code>value</code> as the associated entity erpadm.modeladm.admeo.SmCountryImpl.
     */
    public void setSmCountry(SmCountryImpl value) {
        setAttributeInternal(SMCOUNTRY, value);
    }

    /**
     * @return the associated entity erpadm.modeladm.admeo.SmCityImpl.
     */
    public SmCityImpl getSmCity() {
        return (SmCityImpl) getAttributeInternal(SMCITY);
    }

    /**
     * Sets <code>value</code> as the associated entity erpadm.modeladm.admeo.SmCityImpl.
     */
    public void setSmCity(SmCityImpl value) {
        setAttributeInternal(SMCITY, value);
    }


    /**
     * @param inventoryOrgSno key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer inventoryOrgSno) {
        return new Key(new Object[] { inventoryOrgSno });
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation == DML_INSERT) {
            
            String result =
                ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "INVENTORY_ORG_SNO",
                                                              this.getEntityDef().getSource(), null, null);

            populateAttributeAsChanged(INVENTORYORGSNO, Integer.parseInt(result));
            result =
                ERPGlobalPLSQLClass.doGetPrimaryKeyValueModel(getDBTransaction(), "ORG_SHORT_NAME",
                                                              this.getEntityDef().getSource(), "COMPANY_ID",
                                                              getCompanyId().toString());
            //populateAttributeAsChanged(ORGHIERARCHYPATH,( getParentItemId()==null?getItemId():(getParentItemId()+"-"+getItemId()) ) );
            populateAttributeAsChanged(INVENTORYORGCODE, result);

        }        
        super.doDML(operation, e);
    }
}

