package erpims.modelims.imsvo;

import erpglobals.modelglobals.ERPViewObjectImpl;

import oracle.jbo.server.TransactionEvent;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Jun 28 17:50:12 PKT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvInventoryOrgVOImpl extends ERPViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public InvInventoryOrgVOImpl() {
    }

    /**
     * Returns the variable value for P_ADF_COMPANY_ID.
     * @return variable value for P_ADF_COMPANY_ID
     */
    public Integer getP_ADF_COMPANY_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_COMPANY_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_COMPANY_ID.
     * @param value value to bind as P_ADF_COMPANY_ID
     */
    public void setP_ADF_COMPANY_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_COMPANY_ID", value);
    }

    /**
     * Returns the variable value for P_ADF_INVENTORY_ORG_ID.
     * @return variable value for P_ADF_INVENTORY_ORG_ID
     */
    public Integer getP_ADF_INVENTORY_ORG_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_INVENTORY_ORG_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_INVENTORY_ORG_ID.
     * @param value value to bind as P_ADF_INVENTORY_ORG_ID
     */
    public void setP_ADF_INVENTORY_ORG_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_INVENTORY_ORG_ID", value);
    }

    /**
     * Returns the variable value for P_ADF_LOCATION_ID.
     * @return variable value for P_ADF_LOCATION_ID
     */
    public Integer getP_ADF_LOCATION_ID() {
        return (Integer) ensureVariableManager().getVariableValue("P_ADF_LOCATION_ID");
    }

    /**
     * Sets <code>value</code> for variable P_ADF_LOCATION_ID.
     * @param value value to bind as P_ADF_LOCATION_ID
     */
    public void setP_ADF_LOCATION_ID(Integer value) {
        ensureVariableManager().setVariableValue("P_ADF_LOCATION_ID", value);
    }

    @Override
    public void afterRollback(TransactionEvent transactionEvent) {
        // TODO Implement this method
        setErpPkColumn("InventoryOrgSno");
        setErpParameterId("P_ADF_INVENTORY_ORG_ID");
        setErpViewObjectName("InvInventoryOrgCRUD");
        
        super.afterRollback(transactionEvent);
    }    
    
}

