package erpims.modelims.imsvo;

import erpglobals.modelglobals.ERPViewRowImpl;

import erpims.modelims.imseo.InvPoReceiveHeaderImpl;

import java.sql.Date;
import java.sql.Timestamp;

import oracle.jbo.NameValuePairs;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 20 17:37:22 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvPoReceiveHeaderVORowImpl extends ERPViewRowImpl {
    public static final int ENTITY_INVPORECEIVEHEADER = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PoReceiveHeaderSno,
        PoReceiveHeaderCode,
        PoHeaderSno,
        ShippedDate,
        RfqHeaderSno,
        DeliveryNote,
        DemandHeaderSno,
        CompareHeaderSno,
        ReceiveDate,
        SupplierSno,
        Remarks,
        LocationId,
        InventoryOrgSno,
        GlobalCompanyId,
        CompanyId,
        TempProjectId,
        TempDepartmentId,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        IsSupervised,
        SupervisedBy,
        SupervisedDate,
        IsUnsupervised,
        UnSupervisedBy,
        UnSupervisedDate,
        IsCancelled,
        CancelledBy,
        CancelledDate,
        ApprovalStatusSno,
        DeliveryTermSno,
        txtPoHeaderCode,
        txtLocationName,
        txtSupplierName,
        txtTempProjectName,
        txtTempDepartmentName,
        ReferenceNo,
        txtOrgDescription,
        txtDeliveryTermName,
        InvPoReceiveLinesVO,
        ScmPurchaseOrderHeaderVO,
        AdminCompanyVO,
        ScmSupplierVO,
        GlProjectsVO,
        AdminCompanyVO1,
        InvInventoryOrgVO,
        ScmDeliveryTermVO,
        AccScmPurchaseOrderHeaderVO,
        AccAdminCompanyVO,
        AccScmSupplierVO,
        AccSysApprovalStatusVO,
        AccInvInventoryOrgVO,
        AccAccScmPurchaseOrderLinesVO,
        AccSysSystemParameterVO,
        AccAdminCompanyForCompVO,
        AccSysGeneralValueVO;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int PORECEIVEHEADERSNO = AttributesEnum.PoReceiveHeaderSno.index();
    public static final int PORECEIVEHEADERCODE = AttributesEnum.PoReceiveHeaderCode.index();
    public static final int POHEADERSNO = AttributesEnum.PoHeaderSno.index();
    public static final int SHIPPEDDATE = AttributesEnum.ShippedDate.index();
    public static final int RFQHEADERSNO = AttributesEnum.RfqHeaderSno.index();
    public static final int DELIVERYNOTE = AttributesEnum.DeliveryNote.index();
    public static final int DEMANDHEADERSNO = AttributesEnum.DemandHeaderSno.index();
    public static final int COMPAREHEADERSNO = AttributesEnum.CompareHeaderSno.index();
    public static final int RECEIVEDATE = AttributesEnum.ReceiveDate.index();
    public static final int SUPPLIERSNO = AttributesEnum.SupplierSno.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int LOCATIONID = AttributesEnum.LocationId.index();
    public static final int INVENTORYORGSNO = AttributesEnum.InventoryOrgSno.index();
    public static final int GLOBALCOMPANYID = AttributesEnum.GlobalCompanyId.index();
    public static final int COMPANYID = AttributesEnum.CompanyId.index();
    public static final int TEMPPROJECTID = AttributesEnum.TempProjectId.index();
    public static final int TEMPDEPARTMENTID = AttributesEnum.TempDepartmentId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ISSUPERVISED = AttributesEnum.IsSupervised.index();
    public static final int SUPERVISEDBY = AttributesEnum.SupervisedBy.index();
    public static final int SUPERVISEDDATE = AttributesEnum.SupervisedDate.index();
    public static final int ISUNSUPERVISED = AttributesEnum.IsUnsupervised.index();
    public static final int UNSUPERVISEDBY = AttributesEnum.UnSupervisedBy.index();
    public static final int UNSUPERVISEDDATE = AttributesEnum.UnSupervisedDate.index();
    public static final int ISCANCELLED = AttributesEnum.IsCancelled.index();
    public static final int CANCELLEDBY = AttributesEnum.CancelledBy.index();
    public static final int CANCELLEDDATE = AttributesEnum.CancelledDate.index();
    public static final int APPROVALSTATUSSNO = AttributesEnum.ApprovalStatusSno.index();
    public static final int DELIVERYTERMSNO = AttributesEnum.DeliveryTermSno.index();
    public static final int TXTPOHEADERCODE = AttributesEnum.txtPoHeaderCode.index();
    public static final int TXTLOCATIONNAME = AttributesEnum.txtLocationName.index();
    public static final int TXTSUPPLIERNAME = AttributesEnum.txtSupplierName.index();
    public static final int TXTTEMPPROJECTNAME = AttributesEnum.txtTempProjectName.index();
    public static final int TXTTEMPDEPARTMENTNAME = AttributesEnum.txtTempDepartmentName.index();
    public static final int REFERENCENO = AttributesEnum.ReferenceNo.index();
    public static final int TXTORGDESCRIPTION = AttributesEnum.txtOrgDescription.index();
    public static final int TXTDELIVERYTERMNAME = AttributesEnum.txtDeliveryTermName.index();
    public static final int INVPORECEIVELINESVO = AttributesEnum.InvPoReceiveLinesVO.index();
    public static final int SCMPURCHASEORDERHEADERVO = AttributesEnum.ScmPurchaseOrderHeaderVO.index();
    public static final int ADMINCOMPANYVO = AttributesEnum.AdminCompanyVO.index();
    public static final int SCMSUPPLIERVO = AttributesEnum.ScmSupplierVO.index();
    public static final int GLPROJECTSVO = AttributesEnum.GlProjectsVO.index();
    public static final int ADMINCOMPANYVO1 = AttributesEnum.AdminCompanyVO1.index();
    public static final int INVINVENTORYORGVO = AttributesEnum.InvInventoryOrgVO.index();
    public static final int SCMDELIVERYTERMVO = AttributesEnum.ScmDeliveryTermVO.index();
    public static final int ACCSCMPURCHASEORDERHEADERVO = AttributesEnum.AccScmPurchaseOrderHeaderVO.index();
    public static final int ACCADMINCOMPANYVO = AttributesEnum.AccAdminCompanyVO.index();
    public static final int ACCSCMSUPPLIERVO = AttributesEnum.AccScmSupplierVO.index();
    public static final int ACCSYSAPPROVALSTATUSVO = AttributesEnum.AccSysApprovalStatusVO.index();
    public static final int ACCINVINVENTORYORGVO = AttributesEnum.AccInvInventoryOrgVO.index();
    public static final int ACCACCSCMPURCHASEORDERLINESVO = AttributesEnum.AccAccScmPurchaseOrderLinesVO.index();
    public static final int ACCSYSSYSTEMPARAMETERVO = AttributesEnum.AccSysSystemParameterVO.index();
    public static final int ACCADMINCOMPANYFORCOMPVO = AttributesEnum.AccAdminCompanyForCompVO.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvPoReceiveHeaderVORowImpl() {
    }

    /**
     * Gets InvPoReceiveHeader entity object.
     * @return the InvPoReceiveHeader
     */
    public InvPoReceiveHeaderImpl getInvPoReceiveHeader() {
        return (InvPoReceiveHeaderImpl) getEntity(ENTITY_INVPORECEIVEHEADER);
    }

    /**
     * Gets the attribute value for PO_RECEIVE_HEADER_SNO using the alias name PoReceiveHeaderSno.
     * @return the PO_RECEIVE_HEADER_SNO
     */
    public Integer getPoReceiveHeaderSno() {
        return (Integer) getAttributeInternal(PORECEIVEHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_RECEIVE_HEADER_SNO using the alias name PoReceiveHeaderSno.
     * @param value value to set the PO_RECEIVE_HEADER_SNO
     */
    public void setPoReceiveHeaderSno(Integer value) {
        setAttributeInternal(PORECEIVEHEADERSNO, value);
    }

    /**
     * Gets the attribute value for PO_RECEIVE_HEADER_CODE using the alias name PoReceiveHeaderCode.
     * @return the PO_RECEIVE_HEADER_CODE
     */
    public Integer getPoReceiveHeaderCode() {
        return (Integer) getAttributeInternal(PORECEIVEHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_RECEIVE_HEADER_CODE using the alias name PoReceiveHeaderCode.
     * @param value value to set the PO_RECEIVE_HEADER_CODE
     */
    public void setPoReceiveHeaderCode(Integer value) {
        setAttributeInternal(PORECEIVEHEADERCODE, value);
    }

    /**
     * Gets the attribute value for PO_HEADER_SNO using the alias name PoHeaderSno.
     * @return the PO_HEADER_SNO
     */
    public Integer getPoHeaderSno() {
        return (Integer) getAttributeInternal(POHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_HEADER_SNO using the alias name PoHeaderSno.
     * @param value value to set the PO_HEADER_SNO
     */
    public void setPoHeaderSno(Integer value) {
        setAttributeInternal(POHEADERSNO, value);
        while(getInvPoReceiveLinesVO().getRowCount()>0) {
            getInvPoReceiveLinesVO().first().remove();
        }
        getAccAccScmPurchaseOrderLinesVO().setNamedWhereClauseParam("P_ADF_PO_HEADER_SNO", value==null?-1:value);
        getAccAccScmPurchaseOrderLinesVO().executeQuery();
        RowSetIterator rsi=getAccAccScmPurchaseOrderLinesVO();
        while(rsi.hasNext()) {
            Row nextRow=rsi.next();
            NameValuePairs receiveLinesNP=new NameValuePairs();
            receiveLinesNP.setAttribute("LineNo", getInvPoReceiveLinesVO().getRowCount()+1);
            receiveLinesNP.setAttribute("ItemId", nextRow.getAttribute("ItemId"));
            receiveLinesNP.setAttribute("UnitTypeSno", nextRow.getAttribute("UnitTypeSno"));
            receiveLinesNP.setAttribute("DemandLinesSno", nextRow.getAttribute("DemandLinesSno"));
            receiveLinesNP.setAttribute("CompareSupplierSno", nextRow.getAttribute("CompareSupplierSno"));
            receiveLinesNP.setAttribute("BidLinesSno", nextRow.getAttribute("BidLinesSno"));
            receiveLinesNP.setAttribute("PoLinesSno", nextRow.getAttribute("PoLinesSno"));
            receiveLinesNP.setAttribute("RfqLinesSno", nextRow.getAttribute("RfqLinesSno"));
            receiveLinesNP.setAttribute("SubinventoryOrgSno", nextRow.getAttribute("SubinventoryOrgSno"));
            receiveLinesNP.setAttribute("ReceivedQuantity", nextRow.getAttribute("RemainingBalance"));
            receiveLinesNP.setAttribute("DepartmentId", nextRow.getAttribute("DepartmentId"));
            receiveLinesNP.setAttribute("ProjectId", nextRow.getAttribute("ProjectId"));
            receiveLinesNP.setAttribute("SubinventoryOrgSno", nextRow.getAttribute("SubinventoryOrgSno"));
            receiveLinesNP.setAttribute("ReceiveMethodSno", "1");
            Row initrow=getInvPoReceiveLinesVO().createAndInitRow(receiveLinesNP);
            getInvPoReceiveLinesVO().insertRow(initrow);
            
//         Row newRow=   
        }
    }

    /**
     * Gets the attribute value for SHIPPED_DATE using the alias name ShippedDate.
     * @return the SHIPPED_DATE
     */
    public Date getShippedDate() {
        return (Date) getAttributeInternal(SHIPPEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPPED_DATE using the alias name ShippedDate.
     * @param value value to set the SHIPPED_DATE
     */
    public void setShippedDate(Date value) {
        setAttributeInternal(SHIPPEDDATE, value);
    }

    /**
     * Gets the attribute value for RFQ_HEADER_SNO using the alias name RfqHeaderSno.
     * @return the RFQ_HEADER_SNO
     */
    public Integer getRfqHeaderSno() {
        return (Integer) getAttributeInternal(RFQHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RFQ_HEADER_SNO using the alias name RfqHeaderSno.
     * @param value value to set the RFQ_HEADER_SNO
     */
    public void setRfqHeaderSno(Integer value) {
        setAttributeInternal(RFQHEADERSNO, value);
    }

    /**
     * Gets the attribute value for DELIVERY_NOTE using the alias name DeliveryNote.
     * @return the DELIVERY_NOTE
     */
    public String getDeliveryNote() {
        return (String) getAttributeInternal(DELIVERYNOTE);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_NOTE using the alias name DeliveryNote.
     * @param value value to set the DELIVERY_NOTE
     */
    public void setDeliveryNote(String value) {
        setAttributeInternal(DELIVERYNOTE, value);
    }

    /**
     * Gets the attribute value for DEMAND_HEADER_SNO using the alias name DemandHeaderSno.
     * @return the DEMAND_HEADER_SNO
     */
    public Integer getDemandHeaderSno() {
        return (Integer) getAttributeInternal(DEMANDHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DEMAND_HEADER_SNO using the alias name DemandHeaderSno.
     * @param value value to set the DEMAND_HEADER_SNO
     */
    public void setDemandHeaderSno(Integer value) {
        setAttributeInternal(DEMANDHEADERSNO, value);
    }

    /**
     * Gets the attribute value for COMPARE_HEADER_SNO using the alias name CompareHeaderSno.
     * @return the COMPARE_HEADER_SNO
     */
    public Integer getCompareHeaderSno() {
        return (Integer) getAttributeInternal(COMPAREHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPARE_HEADER_SNO using the alias name CompareHeaderSno.
     * @param value value to set the COMPARE_HEADER_SNO
     */
    public void setCompareHeaderSno(Integer value) {
        setAttributeInternal(COMPAREHEADERSNO, value);
    }

    /**
     * Gets the attribute value for RECEIVE_DATE using the alias name ReceiveDate.
     * @return the RECEIVE_DATE
     */
    public Date getReceiveDate() {
        return (Date) getAttributeInternal(RECEIVEDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVE_DATE using the alias name ReceiveDate.
     * @param value value to set the RECEIVE_DATE
     */
    public void setReceiveDate(Date value) {
        setAttributeInternal(RECEIVEDATE, value);
    }

    /**
     * Gets the attribute value for SUPPLIER_SNO using the alias name SupplierSno.
     * @return the SUPPLIER_SNO
     */
    public Integer getSupplierSno() {
        return (Integer) getAttributeInternal(SUPPLIERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPPLIER_SNO using the alias name SupplierSno.
     * @param value value to set the SUPPLIER_SNO
     */
    public void setSupplierSno(Integer value) {
        setAttributeInternal(SUPPLIERSNO, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for LOCATION_ID using the alias name LocationId.
     * @return the LOCATION_ID
     */
    public Integer getLocationId() {
        return (Integer) getAttributeInternal(LOCATIONID);
    }

    /**
     * Sets <code>value</code> as attribute value for LOCATION_ID using the alias name LocationId.
     * @param value value to set the LOCATION_ID
     */
    public void setLocationId(Integer value) {
        setAttributeInternal(LOCATIONID, value);
        setCompanyId(doGetCompanyIDByLocation(value==null?0:value.intValue(), getGlobalCompanyId()));

    }

    /**
     * Gets the attribute value for INVENTORY_ORG_SNO using the alias name InventoryOrgSno.
     * @return the INVENTORY_ORG_SNO
     */
    public Integer getInventoryOrgSno() {
        return (Integer) getAttributeInternal(INVENTORYORGSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for INVENTORY_ORG_SNO using the alias name InventoryOrgSno.
     * @param value value to set the INVENTORY_ORG_SNO
     */
    public void setInventoryOrgSno(Integer value) {
        setAttributeInternal(INVENTORYORGSNO, value);
    }

    /**
     * Gets the attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @return the GLOBAL_COMPANY_ID
     */
    public Integer getGlobalCompanyId() {
        return (Integer) getAttributeInternal(GLOBALCOMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for GLOBAL_COMPANY_ID using the alias name GlobalCompanyId.
     * @param value value to set the GLOBAL_COMPANY_ID
     */
    public void setGlobalCompanyId(Integer value) {
        setAttributeInternal(GLOBALCOMPANYID, value);
    }

    /**
     * Gets the attribute value for COMPANY_ID using the alias name CompanyId.
     * @return the COMPANY_ID
     */
    public Integer getCompanyId() {
        return (Integer) getAttributeInternal(COMPANYID);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPANY_ID using the alias name CompanyId.
     * @param value value to set the COMPANY_ID
     */
    public void setCompanyId(Integer value) {
        setAttributeInternal(COMPANYID, value);
    }

    /**
     * Gets the attribute value for TEMP_PROJECT_ID using the alias name TempProjectId.
     * @return the TEMP_PROJECT_ID
     */
    public Integer getTempProjectId() {
        return (Integer) getAttributeInternal(TEMPPROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TEMP_PROJECT_ID using the alias name TempProjectId.
     * @param value value to set the TEMP_PROJECT_ID
     */
    public void setTempProjectId(Integer value) {
        setAttributeInternal(TEMPPROJECTID, value);
    }

    /**
     * Gets the attribute value for TEMP_DEPARTMENT_ID using the alias name TempDepartmentId.
     * @return the TEMP_DEPARTMENT_ID
     */
    public Integer getTempDepartmentId() {
        return (Integer) getAttributeInternal(TEMPDEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for TEMP_DEPARTMENT_ID using the alias name TempDepartmentId.
     * @param value value to set the TEMP_DEPARTMENT_ID
     */
    public void setTempDepartmentId(Integer value) {
        setAttributeInternal(TEMPDEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @return the IS_SUPERVISED
     */
    public String getIsSupervised() {
        return (String) getAttributeInternal(ISSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_SUPERVISED using the alias name IsSupervised.
     * @param value value to set the IS_SUPERVISED
     */
    public void setIsSupervised(String value) {
        setAttributeInternal(ISSUPERVISED, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @return the SUPERVISED_BY
     */
    public Integer getSupervisedBy() {
        return (Integer) getAttributeInternal(SUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_BY using the alias name SupervisedBy.
     * @param value value to set the SUPERVISED_BY
     */
    public void setSupervisedBy(Integer value) {
        setAttributeInternal(SUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @return the SUPERVISED_DATE
     */
    public Timestamp getSupervisedDate() {
        return (Timestamp) getAttributeInternal(SUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for SUPERVISED_DATE using the alias name SupervisedDate.
     * @param value value to set the SUPERVISED_DATE
     */
    public void setSupervisedDate(Timestamp value) {
        setAttributeInternal(SUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @return the IS_UNSUPERVISED
     */
    public String getIsUnsupervised() {
        return (String) getAttributeInternal(ISUNSUPERVISED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_UNSUPERVISED using the alias name IsUnsupervised.
     * @param value value to set the IS_UNSUPERVISED
     */
    public void setIsUnsupervised(String value) {
        setAttributeInternal(ISUNSUPERVISED, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @return the UN_SUPERVISED_BY
     */
    public Integer getUnSupervisedBy() {
        return (Integer) getAttributeInternal(UNSUPERVISEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_BY using the alias name UnSupervisedBy.
     * @param value value to set the UN_SUPERVISED_BY
     */
    public void setUnSupervisedBy(Integer value) {
        setAttributeInternal(UNSUPERVISEDBY, value);
    }

    /**
     * Gets the attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @return the UN_SUPERVISED_DATE
     */
    public Timestamp getUnSupervisedDate() {
        return (Timestamp) getAttributeInternal(UNSUPERVISEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for UN_SUPERVISED_DATE using the alias name UnSupervisedDate.
     * @param value value to set the UN_SUPERVISED_DATE
     */
    public void setUnSupervisedDate(Timestamp value) {
        setAttributeInternal(UNSUPERVISEDDATE, value);
    }

    /**
     * Gets the attribute value for IS_CANCELLED using the alias name IsCancelled.
     * @return the IS_CANCELLED
     */
    public String getIsCancelled() {
        return (String) getAttributeInternal(ISCANCELLED);
    }

    /**
     * Sets <code>value</code> as attribute value for IS_CANCELLED using the alias name IsCancelled.
     * @param value value to set the IS_CANCELLED
     */
    public void setIsCancelled(String value) {
        setAttributeInternal(ISCANCELLED, value);
    }

    /**
     * Gets the attribute value for CANCELLED_BY using the alias name CancelledBy.
     * @return the CANCELLED_BY
     */
    public Integer getCancelledBy() {
        return (Integer) getAttributeInternal(CANCELLEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCELLED_BY using the alias name CancelledBy.
     * @param value value to set the CANCELLED_BY
     */
    public void setCancelledBy(Integer value) {
        setAttributeInternal(CANCELLEDBY, value);
    }

    /**
     * Gets the attribute value for CANCELLED_DATE using the alias name CancelledDate.
     * @return the CANCELLED_DATE
     */
    public Timestamp getCancelledDate() {
        return (Timestamp) getAttributeInternal(CANCELLEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CANCELLED_DATE using the alias name CancelledDate.
     * @param value value to set the CANCELLED_DATE
     */
    public void setCancelledDate(Timestamp value) {
        setAttributeInternal(CANCELLEDDATE, value);
    }

    /**
     * Gets the attribute value for APPROVAL_STATUS_SNO using the alias name ApprovalStatusSno.
     * @return the APPROVAL_STATUS_SNO
     */
    public Integer getApprovalStatusSno() {
        return (Integer) getAttributeInternal(APPROVALSTATUSSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for APPROVAL_STATUS_SNO using the alias name ApprovalStatusSno.
     * @param value value to set the APPROVAL_STATUS_SNO
     */
    public void setApprovalStatusSno(Integer value) {
        setAttributeInternal(APPROVALSTATUSSNO, value);
    }

    /**
     * Gets the attribute value for DELIVERY_TERM_SNO using the alias name DeliveryTermSno.
     * @return the DELIVERY_TERM_SNO
     */
    public Integer getDeliveryTermSno() {
        return (Integer) getAttributeInternal(DELIVERYTERMSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DELIVERY_TERM_SNO using the alias name DeliveryTermSno.
     * @param value value to set the DELIVERY_TERM_SNO
     */
    public void setDeliveryTermSno(Integer value) {
        setAttributeInternal(DELIVERYTERMSNO, value);
    }

    /**
     * Gets the attribute value for TXT_PO_HEADER_CODE using the alias name txtPoHeaderCode.
     * @return the TXT_PO_HEADER_CODE
     */
    public Integer gettxtPoHeaderCode() {
        return (Integer) getAttributeInternal(TXTPOHEADERCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PO_HEADER_CODE using the alias name txtPoHeaderCode.
     * @param value value to set the TXT_PO_HEADER_CODE
     */
    public void settxtPoHeaderCode(Integer value) {
        setAttributeInternal(TXTPOHEADERCODE, value);
    }

    /**
     * Gets the attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @return the TXT_LOCATION_NAME
     */
    public String gettxtLocationName() {
        return (String) getAttributeInternal(TXTLOCATIONNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_LOCATION_NAME using the alias name txtLocationName.
     * @param value value to set the TXT_LOCATION_NAME
     */
    public void settxtLocationName(String value) {
        setAttributeInternal(TXTLOCATIONNAME, value);
    }

    /**
     * Gets the attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @return the TXT_SUPPLIER_NAME
     */
    public String gettxtSupplierName() {
        return (String) getAttributeInternal(TXTSUPPLIERNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUPPLIER_NAME using the alias name txtSupplierName.
     * @param value value to set the TXT_SUPPLIER_NAME
     */
    public void settxtSupplierName(String value) {
        setAttributeInternal(TXTSUPPLIERNAME, value);
    }

    /**
     * Gets the attribute value for TXT_TEMP_PROJECT_NAME using the alias name txtTempProjectName.
     * @return the TXT_TEMP_PROJECT_NAME
     */
    public String gettxtTempProjectName() {
        return (String) getAttributeInternal(TXTTEMPPROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_TEMP_PROJECT_NAME using the alias name txtTempProjectName.
     * @param value value to set the TXT_TEMP_PROJECT_NAME
     */
    public void settxtTempProjectName(String value) {
        setAttributeInternal(TXTTEMPPROJECTNAME, value);
    }

    /**
     * Gets the attribute value for TXT_TEMP_DEPARTMENT_NAME using the alias name txtTempDepartmentName.
     * @return the TXT_TEMP_DEPARTMENT_NAME
     */
    public String gettxtTempDepartmentName() {
        return (String) getAttributeInternal(TXTTEMPDEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_TEMP_DEPARTMENT_NAME using the alias name txtTempDepartmentName.
     * @param value value to set the TXT_TEMP_DEPARTMENT_NAME
     */
    public void settxtTempDepartmentName(String value) {
        setAttributeInternal(TXTTEMPDEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for REFERENCE_NO using the alias name ReferenceNo.
     * @return the REFERENCE_NO
     */
    public String getReferenceNo() {
        return (String) getAttributeInternal(REFERENCENO);
    }

    /**
     * Sets <code>value</code> as attribute value for REFERENCE_NO using the alias name ReferenceNo.
     * @param value value to set the REFERENCE_NO
     */
    public void setReferenceNo(String value) {
        setAttributeInternal(REFERENCENO, value);
    }

    /**
     * Gets the attribute value for TXT_ORG_DESCRIPTION using the alias name txtOrgDescription.
     * @return the TXT_ORG_DESCRIPTION
     */
    public String gettxtOrgDescription() {
        return (String) getAttributeInternal(TXTORGDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_ORG_DESCRIPTION using the alias name txtOrgDescription.
     * @param value value to set the TXT_ORG_DESCRIPTION
     */
    public void settxtOrgDescription(String value) {
        setAttributeInternal(TXTORGDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for TXT_DELIVERY_TERM_NAME using the alias name txtDeliveryTermName.
     * @return the TXT_DELIVERY_TERM_NAME
     */
    public String gettxtDeliveryTermName() {
        return (String) getAttributeInternal(TXTDELIVERYTERMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_DELIVERY_TERM_NAME using the alias name txtDeliveryTermName.
     * @param value value to set the TXT_DELIVERY_TERM_NAME
     */
    public void settxtDeliveryTermName(String value) {
        setAttributeInternal(TXTDELIVERYTERMNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link InvPoReceiveLinesVO.
     */
    public RowIterator getInvPoReceiveLinesVO() {
        return (RowIterator) getAttributeInternal(INVPORECEIVELINESVO);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmPurchaseOrderHeaderVO.
     */
    public Row getScmPurchaseOrderHeaderVO() {
        return (Row) getAttributeInternal(SCMPURCHASEORDERHEADERVO);
    }

    /**
     * Sets the master-detail link ScmPurchaseOrderHeaderVO between this object and <code>value</code>.
     */
    public void setScmPurchaseOrderHeaderVO(Row value) {
        setAttributeInternal(SCMPURCHASEORDERHEADERVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO.
     */
    public Row getAdminCompanyVO() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO);
    }

    /**
     * Sets the master-detail link AdminCompanyVO between this object and <code>value</code>.
     */
    public void setAdminCompanyVO(Row value) {
        setAttributeInternal(ADMINCOMPANYVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmSupplierVO.
     */
    public Row getScmSupplierVO() {
        return (Row) getAttributeInternal(SCMSUPPLIERVO);
    }

    /**
     * Sets the master-detail link ScmSupplierVO between this object and <code>value</code>.
     */
    public void setScmSupplierVO(Row value) {
        setAttributeInternal(SCMSUPPLIERVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlProjectsVO.
     */
    public Row getGlProjectsVO() {
        return (Row) getAttributeInternal(GLPROJECTSVO);
    }

    /**
     * Sets the master-detail link GlProjectsVO between this object and <code>value</code>.
     */
    public void setGlProjectsVO(Row value) {
        setAttributeInternal(GLPROJECTSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO1.
     */
    public Row getAdminCompanyVO1() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO1);
    }

    /**
     * Sets the master-detail link AdminCompanyVO1 between this object and <code>value</code>.
     */
    public void setAdminCompanyVO1(Row value) {
        setAttributeInternal(ADMINCOMPANYVO1, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InvInventoryOrgVO.
     */
    public Row getInvInventoryOrgVO() {
        return (Row) getAttributeInternal(INVINVENTORYORGVO);
    }

    /**
     * Sets the master-detail link InvInventoryOrgVO between this object and <code>value</code>.
     */
    public void setInvInventoryOrgVO(Row value) {
        setAttributeInternal(INVINVENTORYORGVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmDeliveryTermVO.
     */
    public Row getScmDeliveryTermVO() {
        return (Row) getAttributeInternal(SCMDELIVERYTERMVO);
    }

    /**
     * Sets the master-detail link ScmDeliveryTermVO between this object and <code>value</code>.
     */
    public void setScmDeliveryTermVO(Row value) {
        setAttributeInternal(SCMDELIVERYTERMVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmPurchaseOrderHeaderVO.
     */
    public RowSet getAccScmPurchaseOrderHeaderVO() {
        return (RowSet) getAttributeInternal(ACCSCMPURCHASEORDERHEADERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyVO.
     */
    public RowSet getAccAdminCompanyVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccScmSupplierVO.
     */
    public RowSet getAccScmSupplierVO() {
        return (RowSet) getAttributeInternal(ACCSCMSUPPLIERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysApprovalStatusVO.
     */
    public RowSet getAccSysApprovalStatusVO() {
        return (RowSet) getAttributeInternal(ACCSYSAPPROVALSTATUSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInvInventoryOrgVO.
     */
    public RowSet getAccInvInventoryOrgVO() {
        return (RowSet) getAttributeInternal(ACCINVINVENTORYORGVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAccScmPurchaseOrderLinesVO.
     */
    public RowSet getAccAccScmPurchaseOrderLinesVO() {
        return (RowSet) getAttributeInternal(ACCACCSCMPURCHASEORDERLINESVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysSystemParameterVO.
     */
    public RowSet getAccSysSystemParameterVO() {
        return (RowSet) getAttributeInternal(ACCSYSSYSTEMPARAMETERVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccAdminCompanyForCompVO.
     */
    public RowSet getAccAdminCompanyForCompVO() {
        return (RowSet) getAttributeInternal(ACCADMINCOMPANYFORCOMPVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValueVO.
     */
    public RowSet getAccSysGeneralValueVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEVO);
    }
}

