package erpims.modelims.imsvo;

import erpglobals.modelglobals.ERPViewRowImpl;

import erpims.modelims.imseo.InvPoReceiveLinesImpl;

import java.math.BigDecimal;

import java.sql.Timestamp;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Aug 27 09:59:13 PKT 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvPoReceiveLinesVORowImpl extends ERPViewRowImpl {

    public static final int ENTITY_INVPORECEIVELINES = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PoReceiveLinesSno,
        PoReceiveHeaderSno,
        PoLinesSno,
        DemandLinesSno,
        CompareSupplierSno,
        RfqLinesSno,
        BidLinesSno,
        LineNo,
        ItemId,
        UnitTypeSno,
        ReceivedQuantity,
        DepartmentId,
        ProjectId,
        CreatedBy,
        CreatedDate,
        LastUpdatedBy,
        LastUpdatedDate,
        ItemRemarks,
        SubinventoryOrgSno,
        ReceiveMethodSno,
        txtItemName,
        txtUnitTypeName,
        txtDepartmentName,
        txtProjectName,
        txtSubinventoryDescription,
        txtPoQuantity,
        InvItemVO,
        InvUnitTypeVO,
        GlProjectsVO,
        AdminCompanyVO,
        InvSubinventoryOrgVO,
        ScmPurchaseOrderLinesVO,
        InvPoReceiveHeaderVO,
        AccInvItemVO,
        AccSysGeneralValueVO,
        AccInvSubinventoryOrgVO;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int PORECEIVELINESSNO = AttributesEnum.PoReceiveLinesSno.index();
    public static final int PORECEIVEHEADERSNO = AttributesEnum.PoReceiveHeaderSno.index();
    public static final int POLINESSNO = AttributesEnum.PoLinesSno.index();
    public static final int DEMANDLINESSNO = AttributesEnum.DemandLinesSno.index();
    public static final int COMPARESUPPLIERSNO = AttributesEnum.CompareSupplierSno.index();
    public static final int RFQLINESSNO = AttributesEnum.RfqLinesSno.index();
    public static final int BIDLINESSNO = AttributesEnum.BidLinesSno.index();
    public static final int LINENO = AttributesEnum.LineNo.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int UNITTYPESNO = AttributesEnum.UnitTypeSno.index();
    public static final int RECEIVEDQUANTITY = AttributesEnum.ReceivedQuantity.index();
    public static final int DEPARTMENTID = AttributesEnum.DepartmentId.index();
    public static final int PROJECTID = AttributesEnum.ProjectId.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATEDDATE = AttributesEnum.CreatedDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int ITEMREMARKS = AttributesEnum.ItemRemarks.index();
    public static final int SUBINVENTORYORGSNO = AttributesEnum.SubinventoryOrgSno.index();
    public static final int RECEIVEMETHODSNO = AttributesEnum.ReceiveMethodSno.index();
    public static final int TXTITEMNAME = AttributesEnum.txtItemName.index();
    public static final int TXTUNITTYPENAME = AttributesEnum.txtUnitTypeName.index();
    public static final int TXTDEPARTMENTNAME = AttributesEnum.txtDepartmentName.index();
    public static final int TXTPROJECTNAME = AttributesEnum.txtProjectName.index();
    public static final int TXTSUBINVENTORYDESCRIPTION = AttributesEnum.txtSubinventoryDescription.index();
    public static final int TXTPOQUANTITY = AttributesEnum.txtPoQuantity.index();
    public static final int INVITEMVO = AttributesEnum.InvItemVO.index();
    public static final int INVUNITTYPEVO = AttributesEnum.InvUnitTypeVO.index();
    public static final int GLPROJECTSVO = AttributesEnum.GlProjectsVO.index();
    public static final int ADMINCOMPANYVO = AttributesEnum.AdminCompanyVO.index();
    public static final int INVSUBINVENTORYORGVO = AttributesEnum.InvSubinventoryOrgVO.index();
    public static final int SCMPURCHASEORDERLINESVO = AttributesEnum.ScmPurchaseOrderLinesVO.index();
    public static final int INVPORECEIVEHEADERVO = AttributesEnum.InvPoReceiveHeaderVO.index();
    public static final int ACCINVITEMVO = AttributesEnum.AccInvItemVO.index();
    public static final int ACCSYSGENERALVALUEVO = AttributesEnum.AccSysGeneralValueVO.index();
    public static final int ACCINVSUBINVENTORYORGVO = AttributesEnum.AccInvSubinventoryOrgVO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public InvPoReceiveLinesVORowImpl() {
    }

    /**
     * Gets InvPoReceiveLines entity object.
     * @return the InvPoReceiveLines
     */
    public InvPoReceiveLinesImpl getInvPoReceiveLines() {
        return (InvPoReceiveLinesImpl) getEntity(ENTITY_INVPORECEIVELINES);
    }

    /**
     * Gets the attribute value for PO_RECEIVE_LINES_SNO using the alias name PoReceiveLinesSno.
     * @return the PO_RECEIVE_LINES_SNO
     */
    public Integer getPoReceiveLinesSno() {
        return (Integer) getAttributeInternal(PORECEIVELINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_RECEIVE_LINES_SNO using the alias name PoReceiveLinesSno.
     * @param value value to set the PO_RECEIVE_LINES_SNO
     */
    public void setPoReceiveLinesSno(Integer value) {
        setAttributeInternal(PORECEIVELINESSNO, value);
    }

    /**
     * Gets the attribute value for PO_RECEIVE_HEADER_SNO using the alias name PoReceiveHeaderSno.
     * @return the PO_RECEIVE_HEADER_SNO
     */
    public Integer getPoReceiveHeaderSno() {
        return (Integer) getAttributeInternal(PORECEIVEHEADERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_RECEIVE_HEADER_SNO using the alias name PoReceiveHeaderSno.
     * @param value value to set the PO_RECEIVE_HEADER_SNO
     */
    public void setPoReceiveHeaderSno(Integer value) {
        setAttributeInternal(PORECEIVEHEADERSNO, value);
    }

    /**
     * Gets the attribute value for PO_LINES_SNO using the alias name PoLinesSno.
     * @return the PO_LINES_SNO
     */
    public Integer getPoLinesSno() {
        return (Integer) getAttributeInternal(POLINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for PO_LINES_SNO using the alias name PoLinesSno.
     * @param value value to set the PO_LINES_SNO
     */
    public void setPoLinesSno(Integer value) {
        setAttributeInternal(POLINESSNO, value);
    }

    /**
     * Gets the attribute value for DEMAND_LINES_SNO using the alias name DemandLinesSno.
     * @return the DEMAND_LINES_SNO
     */
    public Integer getDemandLinesSno() {
        return (Integer) getAttributeInternal(DEMANDLINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for DEMAND_LINES_SNO using the alias name DemandLinesSno.
     * @param value value to set the DEMAND_LINES_SNO
     */
    public void setDemandLinesSno(Integer value) {
        setAttributeInternal(DEMANDLINESSNO, value);
    }

    /**
     * Gets the attribute value for COMPARE_SUPPLIER_SNO using the alias name CompareSupplierSno.
     * @return the COMPARE_SUPPLIER_SNO
     */
    public Integer getCompareSupplierSno() {
        return (Integer) getAttributeInternal(COMPARESUPPLIERSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for COMPARE_SUPPLIER_SNO using the alias name CompareSupplierSno.
     * @param value value to set the COMPARE_SUPPLIER_SNO
     */
    public void setCompareSupplierSno(Integer value) {
        setAttributeInternal(COMPARESUPPLIERSNO, value);
    }

    /**
     * Gets the attribute value for RFQ_LINES_SNO using the alias name RfqLinesSno.
     * @return the RFQ_LINES_SNO
     */
    public Integer getRfqLinesSno() {
        return (Integer) getAttributeInternal(RFQLINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RFQ_LINES_SNO using the alias name RfqLinesSno.
     * @param value value to set the RFQ_LINES_SNO
     */
    public void setRfqLinesSno(Integer value) {
        setAttributeInternal(RFQLINESSNO, value);
    }

    /**
     * Gets the attribute value for BID_LINES_SNO using the alias name BidLinesSno.
     * @return the BID_LINES_SNO
     */
    public Integer getBidLinesSno() {
        return (Integer) getAttributeInternal(BIDLINESSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BID_LINES_SNO using the alias name BidLinesSno.
     * @param value value to set the BID_LINES_SNO
     */
    public void setBidLinesSno(Integer value) {
        setAttributeInternal(BIDLINESSNO, value);
    }

    /**
     * Gets the attribute value for LINE_NO using the alias name LineNo.
     * @return the LINE_NO
     */
    public Integer getLineNo() {
        return (Integer) getAttributeInternal(LINENO);
    }

    /**
     * Sets <code>value</code> as attribute value for LINE_NO using the alias name LineNo.
     * @param value value to set the LINE_NO
     */
    public void setLineNo(Integer value) {
        setAttributeInternal(LINENO, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Integer getItemId() {
        return (Integer) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Integer value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for UNIT_TYPE_SNO using the alias name UnitTypeSno.
     * @return the UNIT_TYPE_SNO
     */
    public Integer getUnitTypeSno() {
        return (Integer) getAttributeInternal(UNITTYPESNO);
    }

    /**
     * Sets <code>value</code> as attribute value for UNIT_TYPE_SNO using the alias name UnitTypeSno.
     * @param value value to set the UNIT_TYPE_SNO
     */
    public void setUnitTypeSno(Integer value) {
        setAttributeInternal(UNITTYPESNO, value);
    }

    /**
     * Gets the attribute value for RECEIVED_QUANTITY using the alias name ReceivedQuantity.
     * @return the RECEIVED_QUANTITY
     */
    public BigDecimal getReceivedQuantity() {
        return (BigDecimal) getAttributeInternal(RECEIVEDQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVED_QUANTITY using the alias name ReceivedQuantity.
     * @param value value to set the RECEIVED_QUANTITY
     */
    public void setReceivedQuantity(BigDecimal value) {
        setAttributeInternal(RECEIVEDQUANTITY, value);
    }

    /**
     * Gets the attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @return the DEPARTMENT_ID
     */
    public Integer getDepartmentId() {
        return (Integer) getAttributeInternal(DEPARTMENTID);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPARTMENT_ID using the alias name DepartmentId.
     * @param value value to set the DEPARTMENT_ID
     */
    public void setDepartmentId(Integer value) {
        setAttributeInternal(DEPARTMENTID, value);
    }

    /**
     * Gets the attribute value for PROJECT_ID using the alias name ProjectId.
     * @return the PROJECT_ID
     */
    public Integer getProjectId() {
        return (Integer) getAttributeInternal(PROJECTID);
    }

    /**
     * Sets <code>value</code> as attribute value for PROJECT_ID using the alias name ProjectId.
     * @param value value to set the PROJECT_ID
     */
    public void setProjectId(Integer value) {
        setAttributeInternal(PROJECTID, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Integer getCreatedBy() {
        return (Integer) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Integer value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATED_DATE using the alias name CreatedDate.
     * @return the CREATED_DATE
     */
    public Timestamp getCreatedDate() {
        return (Timestamp) getAttributeInternal(CREATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_DATE using the alias name CreatedDate.
     * @param value value to set the CREATED_DATE
     */
    public void setCreatedDate(Timestamp value) {
        setAttributeInternal(CREATEDDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Integer getLastUpdatedBy() {
        return (Integer) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Integer value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Timestamp getLastUpdatedDate() {
        return (Timestamp) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Timestamp value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for ITEM_REMARKS using the alias name ItemRemarks.
     * @return the ITEM_REMARKS
     */
    public String getItemRemarks() {
        return (String) getAttributeInternal(ITEMREMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_REMARKS using the alias name ItemRemarks.
     * @param value value to set the ITEM_REMARKS
     */
    public void setItemRemarks(String value) {
        setAttributeInternal(ITEMREMARKS, value);
    }

    /**
     * Gets the attribute value for SUBINVENTORY_ORG_SNO using the alias name SubinventoryOrgSno.
     * @return the SUBINVENTORY_ORG_SNO
     */
    public Integer getSubinventoryOrgSno() {
        return (Integer) getAttributeInternal(SUBINVENTORYORGSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SUBINVENTORY_ORG_SNO using the alias name SubinventoryOrgSno.
     * @param value value to set the SUBINVENTORY_ORG_SNO
     */
    public void setSubinventoryOrgSno(Integer value) {
        setAttributeInternal(SUBINVENTORYORGSNO, value);
    }

    /**
     * Gets the attribute value for RECEIVE_METHOD_SNO using the alias name ReceiveMethodSno.
     * @return the RECEIVE_METHOD_SNO
     */
    public String getReceiveMethodSno() {
        return (String) getAttributeInternal(RECEIVEMETHODSNO);
    }

    /**
     * Sets <code>value</code> as attribute value for RECEIVE_METHOD_SNO using the alias name ReceiveMethodSno.
     * @param value value to set the RECEIVE_METHOD_SNO
     */
    public void setReceiveMethodSno(String value) {
        setAttributeInternal(RECEIVEMETHODSNO, value);
    }

    /**
     * Gets the attribute value for TXT_ITEM_NAME using the alias name txtItemName.
     * @return the TXT_ITEM_NAME
     */
    public String gettxtItemName() {
        return (String) getAttributeInternal(TXTITEMNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_ITEM_NAME using the alias name txtItemName.
     * @param value value to set the TXT_ITEM_NAME
     */
    public void settxtItemName(String value) {
        setAttributeInternal(TXTITEMNAME, value);
    }

    /**
     * Gets the attribute value for TXT_UNIT_TYPE_NAME using the alias name txtUnitTypeName.
     * @return the TXT_UNIT_TYPE_NAME
     */
    public String gettxtUnitTypeName() {
        return (String) getAttributeInternal(TXTUNITTYPENAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_UNIT_TYPE_NAME using the alias name txtUnitTypeName.
     * @param value value to set the TXT_UNIT_TYPE_NAME
     */
    public void settxtUnitTypeName(String value) {
        setAttributeInternal(TXTUNITTYPENAME, value);
    }

    /**
     * Gets the attribute value for TXT_DEPARTMENT_NAME using the alias name txtDepartmentName.
     * @return the TXT_DEPARTMENT_NAME
     */
    public String gettxtDepartmentName() {
        return (String) getAttributeInternal(TXTDEPARTMENTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_DEPARTMENT_NAME using the alias name txtDepartmentName.
     * @param value value to set the TXT_DEPARTMENT_NAME
     */
    public void settxtDepartmentName(String value) {
        setAttributeInternal(TXTDEPARTMENTNAME, value);
    }

    /**
     * Gets the attribute value for TXT_PROJECT_NAME using the alias name txtProjectName.
     * @return the TXT_PROJECT_NAME
     */
    public String gettxtProjectName() {
        return (String) getAttributeInternal(TXTPROJECTNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PROJECT_NAME using the alias name txtProjectName.
     * @param value value to set the TXT_PROJECT_NAME
     */
    public void settxtProjectName(String value) {
        setAttributeInternal(TXTPROJECTNAME, value);
    }

    /**
     * Gets the attribute value for TXT_SUBINVENTORY_DESCRIPTION using the alias name txtSubinventoryDescription.
     * @return the TXT_SUBINVENTORY_DESCRIPTION
     */
    public String gettxtSubinventoryDescription() {
        return (String) getAttributeInternal(TXTSUBINVENTORYDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_SUBINVENTORY_DESCRIPTION using the alias name txtSubinventoryDescription.
     * @param value value to set the TXT_SUBINVENTORY_DESCRIPTION
     */
    public void settxtSubinventoryDescription(String value) {
        setAttributeInternal(TXTSUBINVENTORYDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for TXT_PO_QUANTITY using the alias name txtPoQuantity.
     * @return the TXT_PO_QUANTITY
     */
    public BigDecimal gettxtPoQuantity() {
        return (BigDecimal) getAttributeInternal(TXTPOQUANTITY);
    }

    /**
     * Sets <code>value</code> as attribute value for TXT_PO_QUANTITY using the alias name txtPoQuantity.
     * @param value value to set the TXT_PO_QUANTITY
     */
    public void settxtPoQuantity(BigDecimal value) {
        setAttributeInternal(TXTPOQUANTITY, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InvItemVO.
     */
    public Row getInvItemVO() {
        return (Row) getAttributeInternal(INVITEMVO);
    }

    /**
     * Sets the master-detail link InvItemVO between this object and <code>value</code>.
     */
    public void setInvItemVO(Row value) {
        setAttributeInternal(INVITEMVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InvUnitTypeVO.
     */
    public Row getInvUnitTypeVO() {
        return (Row) getAttributeInternal(INVUNITTYPEVO);
    }

    /**
     * Sets the master-detail link InvUnitTypeVO between this object and <code>value</code>.
     */
    public void setInvUnitTypeVO(Row value) {
        setAttributeInternal(INVUNITTYPEVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link GlProjectsVO.
     */
    public Row getGlProjectsVO() {
        return (Row) getAttributeInternal(GLPROJECTSVO);
    }

    /**
     * Sets the master-detail link GlProjectsVO between this object and <code>value</code>.
     */
    public void setGlProjectsVO(Row value) {
        setAttributeInternal(GLPROJECTSVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link AdminCompanyVO.
     */
    public Row getAdminCompanyVO() {
        return (Row) getAttributeInternal(ADMINCOMPANYVO);
    }

    /**
     * Sets the master-detail link AdminCompanyVO between this object and <code>value</code>.
     */
    public void setAdminCompanyVO(Row value) {
        setAttributeInternal(ADMINCOMPANYVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InvSubinventoryOrgVO.
     */
    public Row getInvSubinventoryOrgVO() {
        return (Row) getAttributeInternal(INVSUBINVENTORYORGVO);
    }

    /**
     * Sets the master-detail link InvSubinventoryOrgVO between this object and <code>value</code>.
     */
    public void setInvSubinventoryOrgVO(Row value) {
        setAttributeInternal(INVSUBINVENTORYORGVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link ScmPurchaseOrderLinesVO.
     */
    public Row getScmPurchaseOrderLinesVO() {
        return (Row) getAttributeInternal(SCMPURCHASEORDERLINESVO);
    }

    /**
     * Sets the master-detail link ScmPurchaseOrderLinesVO between this object and <code>value</code>.
     */
    public void setScmPurchaseOrderLinesVO(Row value) {
        setAttributeInternal(SCMPURCHASEORDERLINESVO, value);
    }

    /**
     * Gets the associated <code>Row</code> using master-detail link InvPoReceiveHeaderVO.
     */
    public Row getInvPoReceiveHeaderVO() {
        return (Row) getAttributeInternal(INVPORECEIVEHEADERVO);
    }

    /**
     * Sets the master-detail link InvPoReceiveHeaderVO between this object and <code>value</code>.
     */
    public void setInvPoReceiveHeaderVO(Row value) {
        setAttributeInternal(INVPORECEIVEHEADERVO, value);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInvItemVO.
     */
    public RowSet getAccInvItemVO() {
        return (RowSet) getAttributeInternal(ACCINVITEMVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccSysGeneralValueVO.
     */
    public RowSet getAccSysGeneralValueVO() {
        return (RowSet) getAttributeInternal(ACCSYSGENERALVALUEVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> AccInvSubinventoryOrgVO.
     */
    public RowSet getAccInvSubinventoryOrgVO() {
        return (RowSet) getAttributeInternal(ACCINVSUBINVENTORYORGVO);
    }
    @Override
    public boolean isAttributeUpdateable(int i) {
        // TODO Implement this method
        if (getInvPoReceiveHeaderVO().getAttribute("IsSupervised").equals("Y") || Integer.parseInt(getInvPoReceiveHeaderVO().getAttribute("ApprovalStatusSno").toString()) >2) {
            return false;
       }
        return super.isAttributeUpdateable(i);
    }
}

